# Используйте официальный образ Golang как базовый
FROM golang:alpine

RUN apk add --no-cache git

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download
COPY . .

RUN go build -o ./cmd/main ./cmd/

EXPOSE 1010

CMD ["./cmd/main"]
